### ISSUE TITLE
Update ruby version in Gemfile and .ruby-version file

### ISSUE THREAD

**Issue by RDegnen** [ga-wdi-boston/ruby-vs-js-objects-inheritence#14]

**Comment by RDegnen** [comment]
update to 2.3.0

**Comment by jrhorn424** [comment]
This should be done via pulling the latest `ruby-template`.

**Comment by gaand** [comment]
We discussed that at one point with mixed results (of actually having that happen).  I hope this will help:https://github.com/ga-wdi-boston/instructors/wiki/Repository-refresh-from-template.

**Comment by berziiii** [comment]
@RDegnen commit c9375d5 should have corrected this. If satisfied, please close.

**Comment by RealWeeks** [comment]
@berziiii I'll speak for @RDegnen  on this one. [In my most Archeresk voice] "LOOKS GOOD".
